name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Linting
    uses: sapphiredev/.github/.github/workflows/reusable-lint.yml@main

  build:
    name: Building
    strategy:
      fail-fast: false
      matrix:
        node: [18, 19, 20, 21]
    uses: sapphiredev/.github/.github/workflows/reusable-build.yml@main
    with:
      node-version: ${{ matrix.node }}

  codeql:
    name: Analysis
    uses: sapphiredev/.github/.github/workflows/reusable-codeql.yml@main
